version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  post_build:
    commands:
      - echo "Build successful"
      - aws s3 cp ./app.zip s3://your-s3-bucket/
artifacts:
  files:
    - '**/*'
  discard-paths: no
